# Case Sensitive!
Chats:
  <Chatname_1>:
    # Rule #1 for Chatname_1. I don't need his fucking messages in this chat
    - username: HateThisGuy
      _action: delete
    # Rule #2 for Chatname_1. Read the messages of this guy automatically 
    - username: TalksToMuch
      _action: autoread
  <Chatname_2>:
    # Rule #1 for Chatname_2. Just print some debug info when he sent a message
    - first_name: John
      second_name: Doe
      _action: print
  # Works in private messages too
  <SomeDude>:
    - _action: autoread